#!/usr/bin/env bash
#/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-benchmarking --enable-extension-timeline-api&
/Users/parroit/.nvm/versions/node/v9.5.0/bin/node /Users/parroit/repos/libui-node/examples/control-gallery.js&
